server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db
    username: root
    password: 43046721
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
    org.springframework.web: INFO